version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=blog_db
      - MYSQL_USER=benutzer
      - MYSQL_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
