spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog_db
    username: benutzer
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Automatische Schemaanpassung deaktiviert, da Flyway nun das Schema managed
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    out-of-order: true

