spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/blog_db
    username: benutzer
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  flyway:
    enabled: false
